# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- task: SonarQubePrepare@7
  inputs:
    SonarQube: 'Sonarqube_Dotnet'
    scannerMode: 'dotnet'
    dotnetScannerVersion: '10.1.1.111189'
    projectKey: 'DotNetOla_DotNetOla_44eb7fcf-8de0-4783-84c7-0c3b7d01c57b'
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
- task: SonarQubePublish@7
  inputs:
    pollingTimeoutSec: '300'
- task: SonarQubeAnalyze@7
  inputs:
    jdkversion: 'JAVA_HOME_17_X64'
- task: Docker@2
  inputs:
    containerRegistry: 'DockerHub'
    repository: 'tayefajem/tayelolu'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: '1'